SELECT ACCT_GEO.*,
LOC_GEO.BID,
LOC_GEO.COUNCIL_DISTRICT
FROM
	(SELECT 
	LOCATION.STREET_NO,
	LOCATION.STREET_PRE_DIRECTION,
	LOCATION.STREET_NAME,
	LOCATION.STREET_SUFFIX,
	LOCATION.STREET_FRACTION,
	LOCATION.APT_SUITE,
	LOCATION.CITY,
	LOCATION.STATE,
	LOCATION.ZIP,
	LOCATION.PO_BOX,
	LOCATION.PMB_BOX,
	LOCATION.OVERRIDE_IND AS LOC_OVERRIDE,
	LOC_ACTIVE.ACCOUNT_KEY,
	LOC_ACTIVE.LOCATION_KEY
	FROM
	(SELECT LOC_HT.ACCOUNT_KEY,
		LOC_HT.LOCATION_KEY
		FROM
		(SELECT
		ACCOUNT_LOCATION_HT.ACCOUNT_KEY,
		ACCOUNT_LOCATION_HT.LOCATION_KEY,
		ROW_NUMBER() OVER (PARTITION BY ACCOUNT_KEY ORDER BY ADDRESS_CHANGE_DT DESC) AS ROW_NO
		FROM ACCOUNT_LOCATION_HT
		WHERE ACTIVE_IND = 'Y') LOC_HT
		WHERE LOC_HT.ROW_NO = 1) LOC_ACTIVE
	LEFT JOIN LOCATION
	ON LOC_ACTIVE.LOCATION_KEY = LOCATION.LOCATION_KEY) ACCT_GEO
LEFT JOIN LOCATION_GEOGRAPHY LOC_GEO
ON ACCT_GEO.LOCATION_KEY = LOC_GEO.LOCATION_KEY