SELECT "ACCOUNT"."BUSINESS_OWNER_NAME", 
"ACCOUNT"."OWNERSHIP_TYPE", 
"ACCOUNT"."ACCOUNT_KEY", 
"ACCOUNT"."EXPIRATION_DT" AS "CERT_EXP_DT",
"ACCOUNT"."EFFECTIVE_DT" AS "CERT_EFF_DT",
"ACCOUNT_STATUS_VT"."DESCRIPTION" AS "ACCOUNT_STATUS",
"DOING_BUS_AS_NAME"."DOING_BUS_AS_NAME" AS "DBA_NAME",
"DOING_BUS_AS_NAME"."PRIMARY_DBA_IND" AS "DBA_NAME_ACTIVE",
"DOING_BUS_AS_NAME"."EFFECTIVE_FROM_DT" AS "DBA_NAME_DT",
"ACCOUNT_LOCATION_HT"."ACTIVE_IND" AS "ADDRESS_ACTIVE",
"ACCOUNT_LOCATION_HT"."ADDRESS_CHANGE_DT" AS "ADDRESS_DT",
"LOCATION"."STREET_NO",
"LOCATION"."STREET_PRE_DIRECTION",
"LOCATION"."STREET_NAME",
"LOCATION"."STREET_SUFFIX",
"LOCATION"."STREET_FRACTION", 
"LOCATION"."APT_SUITE", 
"LOCATION"."CITY", 
"LOCATION"."STATE", 
"LOCATION"."ZIP", 
"NAICS"."DESCRIPTION" AS "NAICS_DESCRIPTION",
"LOCATION"."PO_BOX", 
"LOCATION"."PMB_BOX",
"ACCOUNT"."CREATION_DT",
"ACCOUNT"."BUS_START_DT",
"NAICS"."NAICS" AS "NAICS_CODE"
FROM 
(
	(
		(
			("TTCS"."ACCOUNT" "ACCOUNT"
				INNER JOIN "TTCS"."ACCOUNT_LOCATION_HT" "ACCOUNT_LOCATION_HT"
				ON "ACCOUNT"."ACCOUNT_KEY"="ACCOUNT_LOCATION_HT"."ACCOUNT_KEY")
			INNER JOIN "TTCS"."DOING_BUS_AS_NAME" "DOING_BUS_AS_NAME"
			ON "ACCOUNT"."ACCOUNT_KEY"="DOING_BUS_AS_NAME"."ACCOUNT_KEY")
		INNER JOIN "TTCS"."NAICS" "NAICS" 
		ON "ACCOUNT"."PRIMARY_NAICS"="NAICS"."NAICS")
	INNER JOIN "TTCS"."LOCATION" "LOCATION" 
	ON "ACCOUNT_LOCATION_HT"."LOCATION_KEY"="LOCATION"."LOCATION_KEY")

LEFT JOIN "TTCS"."ACCOUNT_STATUS_VT" "ACCOUNT_STATUS_VT"
ON "ACCOUNT"."ACCOUNT_STATUS" = "ACCOUNT_STATUS_VT"."ACCOUNT_STATUS"

WHERE "ACCOUNT"."ACCOUNT_TYPE"='BTAX'
AND ("ACCOUNT"."ACCOUNT_STATUS"='A' 
	OR "ACCOUNT"."ACCOUNT_STATUS"='I' 
	OR "ACCOUNT"."ACCOUNT_STATUS"='P' 
	OR "ACCOUNT"."ACCOUNT_STATUS"='C' 
	OR "ACCOUNT"."ACCOUNT_STATUS"='N')
AND "ACCOUNT"."DO_NOT_PUBLISH_IND" = 'N'