SELECT ACCOUNT.ACCOUNT_KEY,
ACCOUNT.PIN
FROM ACCOUNT
WHERE ACCOUNT.ACCOUNT_TYPE='BTAX'
AND (ACCOUNT.ACCOUNT_STATUS='A' 
	OR ACCOUNT.ACCOUNT_STATUS='I' 
	OR ACCOUNT.ACCOUNT_STATUS='P')
AND ACCOUNT.DO_NOT_PUBLISH_IND = 'N'