SELECT PHONE.PHONE_NO,
PHONE.PHONE_AREA_CD,
PHONE.PHONE_EXTENSION,
ACCOUNT_PHONE.ACCOUNT_KEY
FROM PHONE
LEFT JOIN ACCOUNT_PHONE
ON PHONE.PHONE_KEY = ACCOUNT_PHONE.PHONE_KEY
WHERE PHONE.ACTIVE_IND = 'Y' 
AND PHONE.PHONE_TYPE='BUS'
AND ACCOUNT_PHONE.ACCOUNT_KEY IS NOT NULL
