SELECT E_MAIL.ADDRESS AS EMAIL,
ACCOUNT_E_MAIL.ACCOUNT_KEY
FROM E_MAIL
LEFT JOIN ACCOUNT_E_MAIL
ON E_MAIL.E_MAIL_KEY = ACCOUNT_E_MAIL.E_MAIL_KEY
WHERE E_MAIL.ACTIVE_IND = 'Y'
AND ACCOUNT_E_MAIL.ACCOUNT_KEY IS NOT NULL
