SELECT ACCT_DBA.*,
NAICS.DESCRIPTION AS NAICS_DESCRIPTION
FROM
(SELECT ACCT_STAT.*,
DOING_BUS_AS_NAME.DOING_BUS_AS_NAME AS DBA_NAME,
DOING_BUS_AS_NAME.PRIMARY_DBA_IND AS DBA_NAME_ACTIVE,
DOING_BUS_AS_NAME.EFFECTIVE_FROM_DT AS DBA_NAME_DT
FROM (SELECT ACCT_MAIN_GEO.*,
	ACCOUNT_STATUS_VT.DESCRIPTION
	FROM
		(SELECT ALL_ACCT_GEO.*,
		ACCOUNT.BUSINESS_OWNER_NAME,
		ACCOUNT.OWNERSHIP_TYPE,
		ACCOUNT.ACCOUNT_KEY,
		ACCOUNT.PRIMARY_NAICS,
		ACCOUNT.EXPIRATION_DT AS CERT_EXP_DT,
		ACCOUNT.EFFECTIVE_DT AS CERT_EFF_DT,
		ACCOUNT.ACCOUNT_STATUS,
		ACCOUNT.CREATION_DT,
		ACCOUNT.BUS_START_DT,
		ACCOUNT.NUM_EMPLOYEES,
		ACCOUNT.HOME_BASED_IND
		FROM
			(SELECT ACCT_GEO.*,
			LOC_GEO.BID,
			LOC_GEO.COUNCIL_DISTRICT
			FROM 
				(SELECT ACCOUNT_LOCATION_HT.ACTIVE_IND AS ADDRESS_ACTIVE,
				ACCOUNT_LOCATION_HT.ADDRESS_CHANGE_DT AS ADDRESS_DT,
				ACCOUNT_LOCATION_HT.ACCOUNT_KEY AS LOC_ACCT_KEY,
				ACCOUNT_LOCATION_HT.LOCATION_KEY,
				LOCATION.STREET_NO,
				LOCATION.STREET_PRE_DIRECTION,
				LOCATION.STREET_NAME,
				LOCATION.STREET_SUFFIX,
				LOCATION.STREET_FRACTION,
				LOCATION.APT_SUITE,
				LOCATION.CITY,
				LOCATION.STATE,
				LOCATION.ZIP,
				LOCATION.PO_BOX,
				LOCATION.PMB_BOX,
				LOCATION.OVERRIDE_IND AS LOC_OVERRIDE
				FROM ACCOUNT_LOCATION_HT
				LEFT JOIN LOCATION
				ON ACCOUNT_LOCATION_HT.LOCATION_KEY = LOCATION.LOCATION_KEY) ACCT_GEO
			LEFT JOIN LOCATION_GEOGRAPHY LOC_GEO
			ON ACCT_GEO.LOCATION_KEY = LOC_GEO.LOCATION_KEY) ALL_ACCT_GEO
		INNER JOIN ACCOUNT
		ON ACCOUNT.ACCOUNT_KEY = ALL_ACCT_GEO.LOC_ACCT_KEY
		WHERE ACCOUNT.EFFECTIVE_DT >= TO_DATE('02/27/2021','mm/dd/yyyy')) ACCT_MAIN_GEO
	LEFT JOIN ACCOUNT_STATUS_VT
	ON ACCT_MAIN_GEO.ACCOUNT_STATUS = ACCOUNT_STATUS_VT.ACCOUNT_STATUS) ACCT_STAT
INNER JOIN DOING_BUS_AS_NAME
ON DOING_BUS_AS_NAME.ACCOUNT_KEY = ACCT_STAT.ACCOUNT_KEY) ACCT_DBA
LEFT JOIN NAICS
ON ACCT_DBA.PRIMARY_NAICS = NAICS.NAICS
