def table_name(mode):
    """Get the name of documnetum tables."""
    if mode == "schedule_24":
        table_name = ['COUNCIL_DOCKETS','COUNCIL_MINUTES','COUNCIL_RESULTS','COUNCIL_DOCKMINRESULTS_ALL',
        'CITY_CHARTER','SCS_CCACTION_CHARTERREV_V','SCS_CCAGENDA_CHARTERREV_V',
        'SCS_CCACTION_BUDGETFINANCE_V','SCS_CCACTION_FIRE_V','SCS_CCACTION_GEO_V','SCS_CCACTION_LUH_V',
        'SCS_CCACTION_NRC_V','SCS_CCACTION_PSNS_V','SCS_CCAGENDA_BUDGETFINANCE_V','SCS_CCAGENDA_EDS_V',
        'SCS_CCAGENDA_FIRE_V','SCS_CCAGENDA_GEO_V','SCS_CCAGENDA_LUH_V','SCS_CCAGENDA_NRC_V',
        'SCS_CCAGENDA_PSNS_V','SCS_REDEVELAGENCY_AGENDAS_V','SCS_REDEVELAGENCY_REPORTS_V',
        'SCS_REDEVELAGENCY_MINUTES_V','SCS_COUNCILDOCKETS_ATTACH_V']
    else:
        table_name = ['LEGAL_OPINIONS','SCS_AGENCY_RESO_ORDINANCE_V','SCS_CCACTION_AUDIT_V',
        'SCS_CCACTION_BGE_V','SCS_CCACTION_EDIR_V','SCS_CCACTION_EDS_V',
        'SCS_CCACTION_ENVIRO_V','SCS_CCACTION_INFRA_V','SCS_CCACTION_PSLN_V',
        'SCS_CCACTION_RULES_OGIR_V','SCS_CCACTION_SGLU_V','SCS_CCAGENDA_AUDIT_V',
        'SCS_CCAGENDA_BGE_V','SCS_CCAGENDA_EDIR_V','SCS_CCAGENDA_ENVIRO_V',
        'SCS_CITYBULLETIN_PUBLICNOT_V','SCS_CCAGENDA_INFRA_V','SCS_REPORTSTOCOUNCIL_V',
        'SCS_CCAGENDA_PSLN_V','SCS_CCAGENDA_RULES_OGIR_V','SCS_CCAGENDA_SGLU_V',
        'SCS_CITYATTORNEYREPORTS_V','SCS_COUNCIL_RESO_ORDINANCE_V','SCS_COUNCILCOMMAGENDAS_ATT_V',
        'SCS_COUNCILPOLICIES_V','SCS_MEMOOFLAW_V','SCS_MUNICODE_HISTORY_V',
        'SCS_MUNICODE_SUPP_V','SCS_MUNICODE_V','SCS_REPORTSTOCOUNCIL_ATTATCH_V',
        'SCS_REPORTSTOCOUNCIL_V','SCS_SPEAKERSLIPS_V']

    return table_name 