SELECT 
"JOB_MAIN"."LOC_WORK_ORDER_LOC", 
"JOB_MAIN"."WORK_ORDER_YR", 
"JOB_MAIN"."WORK_ORDER_NO", 
"JOB_MAIN"."WORK_ORDER_STATUS", 
"JOB_MAIN"."DELAY_STATUS", 
"WDL_MAIN"."DESCRIPTION", 
"JOB_MAIN"."EQ_EQUIP_NO" 
FROM "EMSDBA"."JOB_MAIN" "JOB_MAIN" 
LEFT OUTER JOIN "EMSDBA"."WDL_MAIN" "WDL_MAIN" 
ON "JOB_MAIN"."DELAY_STATUS"="WDL_MAIN"."WDL_WORK_DELAY_CODE" 
WHERE "JOB_MAIN"."WORK_ORDER_STATUS"='OPEN' 
AND (("JOB_MAIN"."DELAY_STATUS" IS NULL ) 
	OR ("JOB_MAIN"."DELAY_STATUS"<>'S')) 
AND NOT ("JOB_MAIN"."LOC_WORK_ORDER_LOC"='LU' 
	OR "JOB_MAIN"."LOC_WORK_ORDER_LOC"='RD') 
ORDER BY "JOB_MAIN"."WORK_ORDER_YR", 
"JOB_MAIN"."LOC_WORK_ORDER_LOC", 
"JOB_MAIN"."DELAY_STATUS", 
"JOB_MAIN"."WORK_ORDER_NO"