SELECT 
eqm.EQ_EQUIP_NO eqm_equip,
eqm.PRI_SHOP_PRIORITY,
eqm.ASSET_TYPE,
eqm.PROCST_PROC_STATUS,
wo.EQ_EQUIP_NO wo_equip,
wo.WORK_ORDER_NO,
wo.delay_status_list
FROM EQ_MAIN eqm
LEFT JOIN
(SELECT EQ_EQUIP_NO,
WORK_ORDER_NO,
LISTAGG(DELAY_STATUS, ', ') WITHIN GROUP (ORDER BY DATETIME_OPEN) AS delay_status_list
FROM JOB_MAIN
WHERE WORK_ORDER_STATUS='OPEN'
AND NOT (LOC_WORK_ORDER_LOC='LU' OR LOC_WORK_ORDER_LOC='RD')
GROUP BY EQ_EQUIP_NO,WORK_ORDER_NO) wo
ON eqm.EQ_EQUIP_NO = wo.EQ_EQUIP_NO