SELECT EQ_EQUIP_NO as equip_id,
WORK_ORDER_NO as wo_id,
PARENT_WO_ID as parent_wo_id,
WORK_ORDER_STATUS as wo_status,
LOC_WORK_ORDER_LOC as work_loc,
JOB_TYPE as job_type,
WORK_ORDER_YR as work_order_year,
DATETIME_OPEN as date_opened,
DATETIME_FINISHED as date_finished,
DATETIME_CLOSED as date_closed,
DATETIME_UNIT_IN as date_unit_in,
METER_1_READING as meter_1,
METER_2_READING as meter_2,
REAS_REAS_FOR_REPAIR as repair_reason,
PRI_PRIORITY_CODE as priority_code,
DEPT_EQUIP_DEPT as dept_code,
LABOR_HOURS as labor_hours,
LABOR_COST as labor_cost,
PARTS_COST as parts_cost,
COMML_COST as comml_cost,
TOTAL_COST as total_cost
FROM EMSDBA.JOB_MAIN