SELECT ORGANIZATION_CODE,
ORGANIZATION_DESC, 
CLAIM_NUMBER, 
ADRESS1, 
ZIP_CODE, 
CITY, 
CLAIMANT_TYPE_DESC, 
CLAIMANT_REFERENCE2_CODE, 
"CLAIMANT_REFERENCE2_Desc", 
INCIDENT_DESC, 
INCIDENT_DATE, 
ADJUSTING_LOC_RECEIVED_DATE, 
ADD_DATE, 
CLOSED_DATE, 
CLAIMANT_STATUS_DESC,
PAID_BI, 
PAID_PD, 
PAID_EXPENSE, 
PAID_TOTAL, 
INCURRED_BI, 
INCURRED_PD, 
INCURRED_EXPENSE, 
INCURRED_TOTAL
FROM CLAIMSTAT.CLAIMSTAT


WHERE SUBSTR ( ORGANIZATION_CODE ,1 , 4 ) = '2116' #TSW
OR SUBSTR ( ORGANIZATION_CODE ,1 , 4 ) = '1914' #PD
OR SUBSTR ( ORGANIZATION_CODE ,1 , 4 ) = '2000' # PUD

AND INCIDENT_DATE >=  date '2008-07-01' 
ORDER BY INCIDENT_DATE DESC


